targets:
  $default:
    builders:
      built_graphql_generator|builder:
        enabled: true
        options:
          schema: todo_app|lib/schema.graphql
          #schema:
          #  path: savvy_app|lib/graphql/schema.graphql
          #  imports:
          #    - package:savvy_app/graphql/scalars/scalars.dart
          #    - package:savvy_app/graphql/base.dart
          #  exports:
          #    - package:savvy_app/graphql/scalars/scalars.dart
          #    - package:savvy_app/graphql/base.dart
          scalars:
            Date: DateTime
            Datetime: DateTime
            FiniteDatetime: DateTime
            UUID: String
            Cursor: String
            JSON: Object
          replaceTypes:
            DatetimeIntervalInput: DatetimeInterval
          irreducibleTypes:
            - name: DatetimeInterval
          #mixins:
          #  - name: Entity
          #    when:
          #      fields:
          #      - entityId
          #      - validFrom
          #      - validUntil
