# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Rebuild IOS and Increment build number"
  lane :build_and_inc_flutter do

    # Return the number of commits in current git branch
    build_number = number_of_commits()

    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "ios",
            "--release",
            "--no-codesign",
            "--build-number=#{build_number}")
    end
  end

  # TODO local version without match and setup
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci(force: true)

    match(type: "appstore", readonly: true)

    build_and_inc_flutter
    build_app(
      xcargs: "-allowProvisioningUpdates",
      export_xcargs: "-allowProvisioningUpdates",
      workspace: "Runner.xcworkspace",
      scheme: "Runner"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

end
