# [START runtime]
runtime: nodejs12
env: standard
entrypoint: node dist/index.js

# manual_scaling:
#   instances: 1
resources:
  cpu: .5
  memory_gb: .5
  disk_size_gb: 10

health_check:
  enable_health_check: False

# [END runtime]
