# TODO It might make more sense to have two different flows for the backend,
# 
on:
  push:
    #paths:
    #  - 'app/*'
    branches:
      - master

jobs:
  deliver-flutter:
    name: Deliver Flutter App Test Builds
    runs-on: macos-latest

    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.0-3.3.pre'
        channel: 'beta'

    - working-directory: "app/"
      run: flutter pub get

    - working-directory: "app/"
      run: flutter pub run build_runner build

      # some packages such as google_sign_in
      # require files that shouldn't be exposed in version control
      # set a github secret with
      # echo "$(base64 -i app/ios/Runner/GoogleService-Info.plist)" | pbcopy
    - name: Write API Key-containing files
      working-directory: "app/"
      run: |
        echo "${{ secrets.APP_GOOGLE_SERVICE_INFO }}" |
          base64 --decode /dev/stdin > ios/Runner/GoogleService-Info.plist

    - name: Write .env
      run: echo 'APP_BASE_URL=${{secrets.APP_BASE_URL}}\n' > app/.env

    - name: Deliver iOS build to testflight
      uses: maierj/fastlane-action@v1.4.0
      with:
        subdirectory: 'app/ios'
        lane: 'beta'

   #- name: Deliver Android build to store
   #  uses: maierj/fastlane-action@v1.4.0
   #  with:
   #    subdirectory: 'app/android'
   #    lane: 'beta'


