# TODO It might make more sense to have two different flows for the backend,
# 
on:
  push:
    #paths:
    #  - 'app/*'
    branches:
      - master

jobs:
  deliver-flutter:
    name: Deliver Flutter App Test Builds
    runs-on: macos-latest

    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.0-3.3.pre'
        channel: 'beta'

    - name: Setup Fastlane
      working-directory: "app/ios"
      run: |
        gem install bundler
        bundle install

    - working-directory: "app/"
      run: flutter pub get

    - working-directory: "app/"
      run: flutter packages pub run build_runner build --delete-conflicting-outputs

      # some packages such as google_sign_in
      # require files that shouldn't be exposed in version control
      # set a github secret with
      # echo "$(base64 -i app/ios/Runner/GoogleService-Info.plist)" | pbcopy
    - name: Write API Key-containing files
      working-directory: "app/"
      run: |
        echo "${{ secrets.APP_GOOGLE_SERVICE_INFO }}" |
          base64 --decode /dev/stdin > ios/Runner/GoogleService-Info.plist

    - name: Write .env
      run: echo 'APP_BASE_URL=${{secrets.APP_BASE_URL}}\n' > app/.env

    - name: Fastlane Match GCS Credentials
      working-directory: "app/ios"
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" |
          base64 --decode /dev/stdin > gc_keys.json

    
    - name: Deliver iOS build to testflight
      working-directory: "app/ios"
      run: bundle exec fastlane beta
      env: 
        FASTLANE_MATCH_GCS_BUCKET: '${{secrets.FASTLANE_MATCH_GCS_BUCKET}}'
        FASTLANE_APPLE_ID: '${{secrets.FASTLANE_APPLE_ID}}'
        FASTLANE_APP_APPLE_ID: '${{secrets.FASTLANE_APP_APPLE_ID}}' # NOTE: ENTIRELY DIFFERENT than the above!
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD}}'

   #- name: Deliver Android build to store
   #  uses: maierj/fastlane-action@v1.4.0
   #  with:
   #    subdirectory: 'app/android'
   #    lane: 'beta'


